# Generated by Django 3.1.1 on 2020-11-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_medicalclinic_medicalvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
