# Generated by Django 3.1.1 on 2020-11-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_auto_20201117_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_patient',
            field=models.BooleanField(default=True),
        ),
    ]
