# Generated by Django 3.1.1 on 2020-11-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_auto_20201123_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specjalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specjalizations',
            field=models.ManyToManyField(to='visits.Specjalization'),
        ),
    ]
