# Generated by Django 3.1.1 on 2020-11-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_auto_20201126_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalclinic',
            options={'ordering': ['city']},
        ),
        migrations.AlterModelOptions(
            name='medicalvisit',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='specjalization',
            options={'ordering': ['name']},
        ),
    ]
