# Generated by Django 3.1.1 on 2021-01-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0011_auto_20210117_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='about_me',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specjalizations',
            field=models.ManyToManyField(null=True, to='visits.Specjalization'),
        ),
    ]
