# Generated by Django 3.1.1 on 2021-01-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0012_auto_20210117_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specjalizations',
            field=models.ManyToManyField(blank=True, to='visits.Specjalization'),
        ),
    ]
