# Generated by Django 3.1.1 on 2021-01-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0013_auto_20210117_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalvisit',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
