# Generated by Django 3.1.1 on 2021-01-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0014_auto_20210117_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablevisits',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_visits', to='visits.doctor'),
        ),
        migrations.AlterField(
            model_name='availablevisits',
            name='medical_clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_visits', to='visits.medicalclinic'),
        ),
        migrations.AlterField(
            model_name='medicalclinic',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_clinic', to='visits.doctor'),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_medical_visits', to='visits.doctor'),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='medical_clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_medical_visits', to='visits.medicalclinic'),
        ),
        migrations.AlterField(
            model_name='medicalvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_visits', to='visits.patient'),
        ),
    ]
